version: '2.3'
services:
  research:
    image: openapparelregistry-research
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/usr/local/src
    working_dir: /usr/local/src
    command: /bin/bash
    cpus: 2
